DROP TABLE IF EXISTS candles_1d;
DROP TABLE IF EXISTS candles_1h;
DROP TABLE IF EXISTS sync_status;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS service_leases;
DROP TABLE IF EXISTS pairs;
DROP TABLE IF EXISTS assets;
