name: CI

permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: make frontend-deps
      - name: Checking types
        run: make frontend-typecheck
      - name: Building source
        run: make frontend-build
      - name: Running tests
        run: make frontend-test

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"
          cache-dependency-path: ./backend/go.sum
      - name: Checking source formatting
        run: make backend-fmt
      - name: Running vet
        run: make backend-vet
      - name: Building backend
        run: make backend-build
      - name: Linting source
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          working-directory: backend
      - name: Run tests
        run: make backend-test

  e2e:
    name: End-to-End Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Compose E2E Tests
        run: make e2e

  load-test:
    name: Load Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Compose Load Tests
        run: make load-test
